In [2]:
%matplotlib inline
import torch
import torchvision
from torch.utils import data
from torchvision import transforms
from torch import nn
from torch.nn import functional as F
from d2l import torch as d2l

import os
os.environ["KMP_DUPLICATE_LIB_OK"]="TRUE"

# 加载和保存张量

对于单个张量，我们可以直接调⽤load和save函数分别读写它们。

这两个函数都要求我们提供⼀个名称，save要求将要保存的变量作为输⼊。

In [4]:
# 保存张量
x = torch.arange(4)
torch.save(x, 'x-file')

In [5]:
# 加载张量
x2 = torch.load('x-file')
x2

tensor([0, 1, 2, 3])

In [6]:
# 存储加载一个张量列表
y = torch.zeros(4)
torch.save([x,y], 'x-files')

x2, y2 = torch.load('x-files')
(x2, y2)

(tensor([0, 1, 2, 3]), tensor([0., 0., 0., 0.]))

In [7]:
# 张量字典
mydict = {'x':x, 'y':y}
torch.save(mydict, 'mydict')

mydict2 = torch.load('mydict')
mydict2

{'x': tensor([0, 1, 2, 3]), 'y': tensor([0., 0., 0., 0.])}

# 加载和保存模型参数

将保存模型的参数而不是保存整个模型

为了恢复模型，我们需要⽤代码⽣成架构，然后从磁盘加载参数。

In [13]:
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(20, 256)
        self.output = nn.Linear(256, 10)
    
    def forward(self, x):
        return self.output(F.relu(self.hidden(x)))

net = MLP()
X = torch.randn(size=(2, 20))
Y = net(X)

In [14]:
# 将模型的参数存储到文件中
torch.save(net.state_dict(), 'mlp.params')

In [18]:
# 为了恢复模型，需要实例化原始多层感知机模型的一个备份
clone = MLP()
clone.load_state_dict(torch.load('mlp.params'))
clone.eval()

MLP(
  (hidden): Linear(in_features=20, out_features=256, bias=True)
  (output): Linear(in_features=256, out_features=10, bias=True)
)

In [19]:
# 由于两个实例具有相同的模型参数，因此在输入相同的X时，实例的计算结果应该相同
Y_clone = clone(X)
Y_clone == Y

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])